// <auto-generated />
using System;
using FS0924_BE_S6_L1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FS0924_BE_S6_L1.Migrations
{
    [DbContext(typeof(PraticaS6L1))]
    [Migration("20250317143008_aggiunta")]
    partial class aggiunta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FS0924_BE_S6_L1.Models.Studente", b =>
                {
                    b.Property<Guid>("StudenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudenteId");

                    b.ToTable("Studenti");

                    b.HasData(
                        new
                        {
                            StudenteId = new Guid("7b3c3520-95c5-4e9b-b7ce-d29eee9319c1"),
                            Cognome = "Tonti",
                            DataDiNascita = new DateTime(1996, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "federico.tonti@gmail.com",
                            Nome = "Federico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
